# Enable for stacktraces
debug: false

# Specifies whether enchantments below should be 
# allowed to ignore the max enchantment levels
enchants-ignore-level-restriction: true

# All custom items belong below here
# items: